version: '3'

services:
    app:
        build: 
          context: .
        container_name: pubnub-test-app
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - '3000:3000'